import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <article className="container-site max-w-[44rem] py-24 md:py-32 prose-styling">
      <span className="eyebrow">
        <span className="rule-line" />
        The Fine Print
      </span>
      <h1 className="mt-4 font-display font-light text-[clamp(2.4rem,5vw,3.6rem)] leading-[1.05] -tracking-tight">
        Privacy <em className="italic text-forest">Policy</em>
      </h1>
      <p className="mt-2 font-display italic text-cocoa/70">
        Last updated: April 2026
      </p>

      <div className="mt-12 space-y-6 text-[1.05rem] leading-[1.7] text-cocoa">
        <p>
          This is a placeholder privacy policy. Before launching, replace this
          with a real policy generated by a service like{" "}
          <a href="https://termly.io" className="underline text-forest">
            Termly
          </a>
          ,{" "}
          <a href="https://www.iubenda.com" className="underline text-forest">
            iubenda
          </a>
          , or reviewed by a lawyer. What follows is the rough shape of what
          yours should cover.
        </p>

        <h2 className="font-display text-2xl text-ink mt-10">
          What we collect
        </h2>
        <p>
          When you submit a contact form, we collect your name, email, and
          message. When you subscribe to the newsletter, we collect your name
          and email. When you make a purchase, our payment partner Lemon
          Squeezy collects billing information needed to process the payment —
          we never see or store your card details.
        </p>

        <h2 className="font-display text-2xl text-ink mt-10">
          How we use your information
        </h2>
        <p>
          To respond to inquiries, deliver the newsletter you signed up for,
          send order confirmations, and fulfil digital products. We don&rsquo;t
          sell your information to anyone, ever.
        </p>

        <h2 className="font-display text-2xl text-ink mt-10">Third parties</h2>
        <p>
          We use the following services: Vercel (hosting), Sanity (content
          storage), Lemon Squeezy (payments &amp; tax), Resend (email
          delivery), Kit (newsletter). Each has its own privacy policy.
        </p>

        <h2 className="font-display text-2xl text-ink mt-10">Your rights</h2>
        <p>
          You can request a copy of the data we hold on you, ask us to delete
          it, or unsubscribe from the newsletter at any time. Email{" "}
          <a href="mailto:hello@essynotes.com" className="underline text-forest">
            hello@essynotes.com
          </a>
          .
        </p>
      </div>
    </article>
  );
}
